---    
- name: Creazione della directory per i dati del registro
  file:
    path: "/Users/lorenzomoro/registry"
    state: directory

- name: Rilevare il motore di container (Docker o Podman)
  command: which_docker
  register: docker_check
  ignore_errors: true

- name: task docker
  include_task: docker.yml
  when: docker_check.rc == 0

- name: task podman
  include_task: podman.yml
  when: docker_check.rc != 0
