pipeline {
    agent any
    environment {
        REGISTRY_URL = 'localhost:5000'
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('Track3_Step5') {
                    script {
                        def tag = "build-${env.BUILD_NUMBER}"
                        def imageName = "App-prova:${tag}"


                        def image = docker.build(imageName)

                        docker.withRegistry("http://${env.REGISTRY_URL}", "registry-credentials") {
                            image.push()
                        }

                        sh "docker rmi --force ${imageName}"
                    }
                }
            }
        }
    }
}
