pipeline {
    agent any
    environment {
        REGISTRY_URL = 'localhost:5000'
        REGISTRY_CREDENTIALS = 'registry-credentials'
    }

	stages {
        
		stage('Clone repository') {
			steps {
				checkout scm
			}
		}

        stage('Build and Push Docker Image') {
            steps {
                dir('Track3_Step5') {
                    script {
                        def tag = "build-${env.BUILD_NUMBER}"
                        
                        docker.withRegistry("http://localhost:5000", REGISTRY_CREDENTIALS) {
                            def image = docker.build("localhost:5000/Prova_build:${tag}")
                            image.push()
                    }
                    sh "docker rmi --force localhost:5000/Prova_build:${tag}"
                    }
                }
            }
        }
    }
}