---
- name: Create image for container 1
  containers.podman.podman_image:
    name: "localhost:5000/ubuntu_ssh"
    path: "/Users/lorenzomoro/progetto/ubuntu_ssh"
    tag: latest

- name: Create image for container 1
  containers.podman.podman_image:
    name: "localhost:5000/debian_ssh"
    path: "/Users/lorenzomoro/progetto/debian_ssh"
    tag: latest