---
- name: Push image ubuntu_ssh
  community.docker.docker_image:
    name: "localhost:5000/ubuntu_ssh"
    tag: latest
    push: yes
    source: "local"

- name: Push image debian_ssh
  community.docker.docker_image:
    name: "localhost:5000/debian_ssh"
    tag: latest
    push: yes
    source: "local"