---
- name: Start container ubuntu_ssh
  containers.podman.podman_container:
    name: ubuntu_ssh
    image: "localhost:5000/ubuntu_ssh:latest"
    ports:
      - "2222:22"
    state: started

- name: Start container debian_ssh
  containers.podman.podman_container:
    name: debian_ssh
    image: "localhost:5000/debian_ssh:latest"
    ports:
      - "2223:22"
    state: started