---    
- name: Create directory for registry
  file:
    path: "/Users/lorenzomoro/registry"
    state: directory

- name: Create directory for registry auth
  file:
    path: "/Users/lorenzomoro/registry/auth"
    state: directory

- name: Check docker or podman
  command: which docker
  register: docker_check
  ignore_errors: true

# - name: Login al registro Docker
#  community.docker.docker_login:
#    registry_url: "localhost:5000"
#    username: "{{ registry_user }}"
#    password: "{{ registry_password }}"

- name: task docker
  include_tasks: docker.yml
  when: docker_check.rc == 0

- name: task podman
  include_tasks: podman.yml
  when: docker_check.rc != 0
